######################################################################
# Automatically generated by qmake (3.0) Sun Dec 16 22:09:55 2018
######################################################################
QT += core gui widgets
TEMPLATE = app
TARGET = qtTest
INCLUDEPATH += .

# Input
HEADERS += helloworldwindow.h
SOURCES += helloworld.cpp helloworldwindow.cpp
